default:
	rm -f devsecops_et_infrastructure.pdf
	latexmk -output-directory=output -xelatex devsecops_et_infrastructure.tex
	ln -s ./output/devsecops_et_infrastructure.pdf devsecops_et_infrastructure.pdf